"""Base agent with reasoning, memory, and gateway routing."""
from __future__ import annotations

import asyncio
import json
from pathlib import Path
from typing import List, Dict, Optional, Any

from .llm import chat_with_tools
from .tools import TOOL_DEFS
from .state import Hub, Task, TaskStatus
from .memory import Memory
from .reasoning import Reasoner


class Agent:
    """An autonomous agent that REASONS, then acts, then reflects.

    Cognitive loop per task:
    1. REASON — analyze the task, generate hypotheses, plan approach
    2. ACT — use tools (web search, file ops, code) guided by the plan
    3. REFLECT — assess what was accomplished, store insights in memory

    All tool calls routed through Gateway for access control + auditing.
    """

    def __init__(
        self,
        name: str,
        role: str,
        hub: Hub,
        workspace: Path,
        model: str = "gpt-4.1-nano",
        gateway: Any = None,
        memory: Optional[Memory] = None,
        depth: int = 0,
    ):
        self.name = name
        self.role = role
        self.hub = hub
        self.workspace = workspace
        self.workspace.mkdir(parents=True, exist_ok=True)
        self.model = model
        self.gateway = gateway
        self.memory = memory
        self.depth = depth
        self.reasoner = Reasoner(model=model)
        self._log_lines: List[str] = []

    def _get_memory_context(self, task_description: str) -> str:
        """Search persistent memory for relevant prior knowledge."""
        if not self.memory:
            return ""

        words = task_description.split()
        search_terms = [w for w in words if len(w) > 4][:5]
        query = " ".join(search_terms) if search_terms else task_description[:50]

        entries = self.memory.search(query, limit=5)
        if not entries:
            return ""

        lessons = self.memory.get_lessons(applies_to=query, limit=3)

        context = self.memory.format_for_context(entries, max_chars=2000)
        if lessons:
            context += "\n\nLESSONS FROM PAST EXPERIENCE:"
            for l in lessons:
                context += f"\n  What happened: {l['what_happened'][:100]}"
                context += f"\n  Lesson: {l['what_learned'][:100]}\n"

        return context

    async def _reason_about_task(self, task_description: str) -> str:
        """Phase 1: REASON — think before acting.

        Uses the reasoning engine to:
        - Understand what's really being asked
        - Identify key unknowns
        - Plan an approach
        - Generate hypotheses if applicable
        """
        self._log("Reasoning about task...")

        # Chain-of-thought analysis
        reasoning = await self.reasoner.think_step_by_step(
            problem=task_description,
            context=self._get_memory_context(task_description),
        )

        # Build reasoning context for the agent
        lines = ["REASONING (think before you act):"]
        lines.append(f"  Understanding: {reasoning.get('understanding', 'N/A')}")

        assumptions = reasoning.get("assumptions", [])
        if assumptions:
            lines.append(f"  Assumptions: {'; '.join(str(a) for a in assumptions[:3])}")

        steps = reasoning.get("steps", [])
        if steps:
            lines.append("  Planned steps:")
            for s in steps[:5]:
                lines.append(f"    {s.get('step', '?')}. {s.get('reasoning', 'N/A')}")

        insight = reasoning.get("key_insight", "")
        if insight:
            lines.append(f"  Key insight: {insight}")

        unknowns = reasoning.get("unknowns", [])
        if unknowns:
            lines.append(f"  Must find out: {'; '.join(str(u) for u in unknowns[:3])}")

        confidence = reasoning.get("confidence", 0.5)
        lines.append(f"  Confidence: {confidence:.0%}")

        self._log(f"Reasoning complete (confidence: {confidence:.0%})")
        return "\n".join(lines)

    def _system_prompt(self, task_description: str, reasoning_context: str) -> str:
        memory_context = self._get_memory_context(task_description)
        memory_section = f"\n\nPRIOR KNOWLEDGE:\n{memory_context}" if memory_context else ""

        return f"""You are {self.name}, a specialized AI agent in a multi-agent system.

YOUR ROLE: {self.role}

YOUR CURRENT TASK: {task_description}

{reasoning_context}

YOUR WORKSPACE: {self.workspace}
Save any outputs (research findings, analysis, data files) to your workspace directory.

INTER-AGENT COMMUNICATION:
- Use send_message to share findings with other agents or the orchestrator.
- You can send to: "orchestrator", "ResearchAgent", "AnalystAgent", "WriterAgent", or any specialist.
{memory_section}
COGNITIVE GUIDELINES:
- Follow the reasoning plan above. It was generated by careful analysis of your task.
- Investigate the unknowns identified in the reasoning.
- Use web_search to find real information. Don't make things up.
- If your initial approach isn't working, ADAPT — try a different angle.
- You can dynamically **delegate sub-tasks** to specialized agents using the `delegate_task` tool. This spawns them in the background so you can keep working or spawn more!
- If you run into a blocker, broadcast a message to the "SwarmChannel" (using send_message) to ask if any other agent can help you (e.g. asking for a Python package or database built).
- Save important findings to files in your workspace using write_file.
- Be specific and concrete. Cite sources when possible.
- When done, provide: (1) key findings, (2) confidence level, (3) what remains unknown.
"""

    def _get_tool_handlers(self) -> Dict:
        if self.gateway:
            handlers = dict(self.gateway.make_tool_handlers(self.name))
        else:
            from .tools import TOOL_HANDLERS
            handlers = dict(TOOL_HANDLERS)

        async def handle_write_file(path: str, content: str) -> str:
            # Force strictly to workspace to prevent "gunk"
            safe_name = Path(path).name
            full_path = str(self.workspace / safe_name)
            if self.gateway:
                return await self.gateway.invoke_tool(self.name, "write_file", {"path": full_path, "content": content})
            from .tools import write_file
            return await write_file(full_path, content)
            
        handlers["write_file"] = handle_write_file

        async def handle_delegate_task(specialty: str, task: str) -> str:
            if self.depth >= 5:
                return "Error: Maximum Swarm recursion depth (5) reached. You must resolve this task yourself without delegating further."
                
            from .agent import create_specialist_agent
            import uuid
            
            # Create a safe name for the sub-agent
            safe_domain = specialty.replace(' ', '_').replace('-', '_')[:20]
            name = f"Specialist_{safe_domain}_{uuid.uuid4().hex[:4]}"
            
            sub_agent = create_specialist_agent(
                name=name, specialty=specialty,
                hub=self.hub, workspace=self.workspace.parent / name.lower(),
                model=self.model, gateway=self.gateway, memory=self.memory,
                depth=self.depth + 1
            )
            
            if self.gateway:
                self.gateway.register_agent(name, sub_agent)
                
            task_id = f"del_{uuid.uuid4().hex[:6]}"
            from .state import Task
            t = Task(id=task_id, description=f"[Delegated from {self.name}] {task}. When complete, summarize and send_message back to {self.name}.")
            self.hub.add_task(t)
            
            self._log(f"Spawning background sub-agent '{name}' for task '{task_id}'...")
            
            # Non-blocking Swarm execution
            asyncio.create_task(sub_agent.execute(t))
            
            return f"Success. Sub-agent '{name}' spawned in the background for: {task}. They will send_message to '{self.name}' when complete. You may continue working or spawn additional parallel agents."

        handlers["delegate_task"] = handle_delegate_task
        return handlers

    async def execute(self, task: Task) -> str:
        """Execute a task using the REASON -> ACT -> REFLECT loop."""
        
        if self.gateway:
            self.gateway.register_task(task.id)
            
        self.hub.set_agent_status(self.name, "working", task.id)
        self.hub.update_task(task.id, status="in_progress", assigned_to=self.name)

        self._log(f"Starting task: {task.description[:80]}")

        # ── Phase 1: REASON ──────────────────────────────────────
        reasoning_context = await self._reason_about_task(task.description)

        # Check for messages from other agents
        messages_from_others = self.hub.get_messages(self.name)
        context_msgs = ""
        if messages_from_others:
            context_msgs = "\n\nMESSAGES FROM OTHER AGENTS:\n"
            for m in messages_from_others[-5:]:
                context_msgs += f"  From {m['sender']}: {m['content'][:300]}\n"

        # ── Phase 2: ACT ─────────────────────────────────────────
        messages = [
            {"role": "system", "content": self._system_prompt(task.description, reasoning_context)},
            {"role": "user", "content": (
                f"Execute this task now:\n\n{task.description}\n\n"
                f"Follow your reasoning plan. Use your tools. Produce concrete results."
                f"{context_msgs}"
            )},
        ]

        tool_handlers = self._get_tool_handlers()

        async def on_tool_call(tool_name, args, result_preview):
            if self.gateway:
                await self.gateway.check_interrupt(task.id, self.name)
            self._log(f"  tool: {tool_name}({str(args)[:60]}...)")

        try:
            if self.gateway:
                await self.gateway.check_interrupt(task.id, self.name)
                
            result = await chat_with_tools(
                messages=messages,
                tool_defs=TOOL_DEFS,
                tool_handlers=tool_handlers,
                model=self.model,
                max_rounds=15,
                on_tool_call=on_tool_call,
            )

            self.hub.update_task(task.id, status="done", result=result[:2000])
            self.hub.set_agent_status(self.name, "idle")
            self._log(f"Completed task: {task.description[:60]}...")

            # Save result to workspace
            result_path = self.workspace / f"result_{task.id[:8]}.md"
            result_path.write_text(f"# Task: {task.description}\n\n## Reasoning\n{reasoning_context}\n\n## Result\n{result}")

            # ── Phase 3: REFLECT (store insights) ────────────────
            if self.memory and result and len(result) > 50:
                self.memory.store(
                    topic=task.description[:100],
                    content=result[:500],
                    category="research" if "Research" in self.name else "analysis",
                    source=self.name,
                    project=str(self.workspace.parent.parent.name),
                    confidence=0.6,
                )

            return result

        except asyncio.CancelledError as e:
            error_msg = f"Task Terminated via Mission Control: {e}"
            self.hub.update_task(task.id, status="killed", result=error_msg)
            self.hub.set_agent_status(self.name, "idle")
            self._log(error_msg)
            return error_msg
        except Exception as e:
            error_msg = f"Failed: {e}"
            self.hub.update_task(task.id, status="failed", result=error_msg)
            self.hub.set_agent_status(self.name, "error")
            self._log(error_msg)

            if self.memory:
                self.memory.store_lesson(
                    what_happened=f"{self.name} failed on: {task.description[:100]}. Error: {str(e)[:200]}",
                    what_learned=f"Task type '{task.description[:50]}' may need different approach or model",
                    applies_to=task.description[:50],
                    project=str(self.workspace.parent.parent.name),
                )

            return error_msg

    def _log(self, message: str):
        line = f"[{self.name}] {message}"
        self._log_lines.append(line)
        print(line)


# ── Specialized Agent Factories ──────────────────────────────────────

def create_research_agent(hub: Hub, workspace: Path, model: str = "gpt-4.1-nano",
                          gateway: Any = None, memory: Optional[Memory] = None, depth: int=0) -> Agent:
    return Agent(
        name="ResearchAgent",
        role=(
            "You are a research specialist. Your job is to search the web for high-quality, "
            "accurate information on the given topic. Find scientific papers, news articles, "
            "expert opinions, and data. Synthesize findings into clear, well-organized reports. "
            "Always cite your sources with URLs."
        ),
        hub=hub, workspace=workspace / "research", model=model,
        gateway=gateway, memory=memory, depth=depth,
    )


def create_analyst_agent(hub: Hub, workspace: Path, model: str = "gpt-4.1-nano",
                         gateway: Any = None, memory: Optional[Memory] = None, depth: int=0) -> Agent:
    return Agent(
        name="AnalystAgent",
        role=(
            "You are a data analyst and critical thinker. Your job is to analyze information, "
            "identify patterns, evaluate evidence quality, find gaps in knowledge, and produce "
            "structured analyses. Use Python for calculations and data processing when needed. "
            "Be rigorous and evidence-based."
        ),
        hub=hub, workspace=workspace / "analysis", model=model,
        gateway=gateway, memory=memory, depth=depth,
    )


def create_writer_agent(hub: Hub, workspace: Path, model: str = "gpt-4.1-nano",
                        gateway: Any = None, memory: Optional[Memory] = None, depth: int=0) -> Agent:
    return Agent(
        name="WriterAgent",
        role=(
            "You are a synthesis and writing specialist. Your job is to take research findings "
            "and analyses from other agents, and produce clear, comprehensive, well-structured "
            "reports. Focus on actionable insights and clear communication. Save final reports "
            "to your workspace."
        ),
        hub=hub, workspace=workspace / "reports", model=model,
        gateway=gateway, memory=memory, depth=depth,
    )


def create_specialist_agent(
    name: str, specialty: str, hub: Hub, workspace: Path,
    model: str = "gpt-4.1-nano", gateway: Any = None,
    memory: Optional[Memory] = None, depth: int = 0,
) -> Agent:
    return Agent(
        name=name,
        role=f"You are a specialist in: {specialty}. Apply your expertise to the given task.",
        hub=hub, workspace=workspace / name.lower(), model=model,
        gateway=gateway, memory=memory, depth=depth,
    )
